/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbms;

import static dbms.createRoom.RoomId;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Yaseen
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    
    Connection c = dbms.Dbms.DBcon();
    PreparedStatement st = null;
    ResultSet rs;
    
    public static createRoom cr = new createRoom();
    public static roomManage rm = new roomManage();
    public static roomDiscover rd = new roomDiscover();
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        crp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jrp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        orp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jorp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 17, 17));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/output-onlinepngtools.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("OCR A Std", 0, 36)); // NOI18N
        jLabel1.setText("Main Menu");

        crp.setBackground(new java.awt.Color(17, 17, 17));
        crp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crpMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create Room");

        javax.swing.GroupLayout crpLayout = new javax.swing.GroupLayout(crp);
        crp.setLayout(crpLayout);
        crpLayout.setHorizontalGroup(
            crpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crpLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        crpLayout.setVerticalGroup(
            crpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crpLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(79, 79, 79))
        );

        jrp.setBackground(new java.awt.Color(17, 17, 17));
        jrp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrpMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Join Room");

        javax.swing.GroupLayout jrpLayout = new javax.swing.GroupLayout(jrp);
        jrp.setLayout(jrpLayout);
        jrpLayout.setHorizontalGroup(
            jrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jrpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(87, 87, 87))
        );
        jrpLayout.setVerticalGroup(
            jrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jrpLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        orp.setBackground(new java.awt.Color(17, 17, 17));
        orp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orpMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Owned Rooms");

        javax.swing.GroupLayout orpLayout = new javax.swing.GroupLayout(orp);
        orp.setLayout(orpLayout);
        orpLayout.setHorizontalGroup(
            orpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orpLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        orpLayout.setVerticalGroup(
            orpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orpLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(77, 77, 77))
        );

        jorp.setBackground(new java.awt.Color(17, 17, 17));
        jorp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jorpMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Joined Rooms");

        javax.swing.GroupLayout jorpLayout = new javax.swing.GroupLayout(jorp);
        jorp.setLayout(jorpLayout);
        jorpLayout.setHorizontalGroup(
            jorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jorpLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(64, 64, 64))
        );
        jorpLayout.setVerticalGroup(
            jorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jorpLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jorp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jorp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crpMouseClicked
        cr.setVisible(true);
    }//GEN-LAST:event_crpMouseClicked

    private void jrpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrpMouseClicked
        String rid = JOptionPane.showInputDialog(null, "Enter Room code", "Enter", JOptionPane.QUESTION_MESSAGE);
        try {
            st = c.prepareStatement("INSERT INTO JOIN_ROOM (rid, uun) VALUES (?,?)");
            st.setString(1, rid);
            st.setString(2, Dbms.userData.getUser());
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Joined successfully");
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jrpMouseClicked

    private void orpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orpMouseClicked
        JComboBox<String> comboBox = new JComboBox<>();
        ArrayList<String> ou = new ArrayList();
        int cc = 0;
        try{
            st = c.prepareStatement("SELECT * FROM room WHERE creator = (?) ORDER BY creationDate DESC");
            st.setString(1, Dbms.userData.getUser());
            rs = st.executeQuery();
            
            while(rs.next()){
                ou.add(rs.getString("rid"));
                comboBox.addItem(rs.getString("name"));
                cc++;
            }
        }catch(SQLException exc){
            System.out.println(exc);
        }
        try{
            st = c.prepareStatement("SELECT * FROM ROOM AS R, ROOM_ADMINS AS A WHERE (R.rid = A.rid) AND (A.uun = ?)");
            st.setString(1, Dbms.userData.getUser());
            rs = st.executeQuery();
            
            while(rs.next()){
                ou.add(rs.getString("rid"));
                comboBox.addItem(rs.getString("name") + " (Admin)");
            }
        }catch(SQLException exc){
            System.out.println(exc);
        }
        

        // Set the OCR font
        Font ocrFont = new Font("OCR A Extended", Font.PLAIN, 18);
        comboBox.setFont(ocrFont);

        JPanel panel = new JPanel();
        JLabel aslabel = new JLabel("Select a class to open : ");
        aslabel.setFont(ocrFont);
        panel.add(aslabel);
        panel.add(comboBox);
        panel.setFont(ocrFont);

        int result = JOptionPane.showOptionDialog(null, panel, "Owned Classes",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, null, null);

        if (result == JOptionPane.OK_OPTION) {
            int selectedOption = comboBox.getSelectedIndex();
            Dbms.currentRoom.setRoom(ou.get(selectedOption));
            Dbms.currentRoom.setRoomName((String)comboBox.getSelectedItem());
            rm.setVisible(true);
            if(selectedOption > cc){
                roomManage.AddAdmin.setVisible(false);
            }
            roomManage.roomName.setText(Dbms.currentRoom.getRoomName());
        }
    }//GEN-LAST:event_orpMouseClicked

    private void jorpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jorpMouseClicked
        JComboBox<String> comboBox = new JComboBox<>();
        ArrayList<String> ou = new ArrayList();

        try{
            st = c.prepareStatement("SELECT * FROM ROOM AS R, join_room AS A WHERE (R.rid = A.rid) AND (A.uun = ?)");
            st.setString(1, Dbms.userData.getUser());
            rs = st.executeQuery();
            
            while(rs.next()){
                ou.add(rs.getString("rid"));
                comboBox.addItem(rs.getString("name"));
            }
        }catch(SQLException exc){
            System.out.println(exc);
        }
        

        // Set the OCR font
        Font ocrFont = new Font("OCR A Extended", Font.PLAIN, 18);
        comboBox.setFont(ocrFont);

        JPanel panel = new JPanel();
        JLabel aslabel = new JLabel("Select a class to open : ");
        aslabel.setFont(ocrFont);
        panel.add(aslabel);
        panel.add(comboBox);
        panel.setFont(ocrFont);

        int result = JOptionPane.showOptionDialog(null, panel, "Joined Classes",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, null, null);

        if (result == JOptionPane.OK_OPTION) {
            int selectedOption = comboBox.getSelectedIndex();
            Dbms.currentRoom.setRoom(ou.get(selectedOption));
            Dbms.currentRoom.setRoomName((String)comboBox.getSelectedItem());
            rd.setVisible(true);
            roomDiscover.roomName.setText(Dbms.currentRoom.getRoomName());
        }
        //roomManage.roomName.setText(Dbms.currentRoom.getRoomName());
    }//GEN-LAST:event_jorpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel crp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jorp;
    private javax.swing.JPanel jrp;
    private javax.swing.JPanel orp;
    // End of variables declaration//GEN-END:variables
}
