/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbms;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author h.d
 */
public class makeQuiz extends javax.swing.JFrame {

    /**
     * Creates new form Make_Quize
     */
    public makeQuiz() {
        initComponents();
    }
    Connection c = dbms.Dbms.DBcon();
    PreparedStatement st = null;// to insert and apdate on the database.(Updates)
    ResultSet rs;
    static String qid = "";
    static int QuesNo = 0;
    public static setQuestions SQU = new setQuestions(); 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        QuestionNumberTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        YesRadioButton = new javax.swing.JRadioButton();
        NoRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        YearTextField = new javax.swing.JTextField();
        MonthTextField = new javax.swing.JTextField();
        DayTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        HourTextField = new javax.swing.JTextField();
        MinutesTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(17, 17, 17));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/output-onlinepngtools.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setText("Quizes Settings");

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel2.setText("Title");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setText("Number of questions");

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel4.setText("Do you Want tot display grade to users?");

        titleTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextFieldActionPerformed(evt);
            }
        });
        titleTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                titleTextFieldKeyPressed(evt);
            }
        });

        QuestionNumberTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        QuestionNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QuestionNumberTextFieldKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("OCR A Extended", 2, 14)); // NOI18N
        jButton1.setText("Next ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(YesRadioButton);
        YesRadioButton.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        YesRadioButton.setSelected(true);
        YesRadioButton.setText("Yes");

        buttonGroup1.add(NoRadioButton);
        NoRadioButton.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        NoRadioButton.setText("No");

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel5.setText("End date");

        YearTextField.setForeground(java.awt.Color.lightGray);
        YearTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                YearTextFieldFocusGained(evt);
            }
        });
        YearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearTextFieldActionPerformed(evt);
            }
        });
        YearTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                YearTextFieldKeyPressed(evt);
            }
        });

        MonthTextField.setForeground(java.awt.Color.lightGray);
        MonthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthTextFieldActionPerformed(evt);
            }
        });
        MonthTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MonthTextFieldKeyPressed(evt);
            }
        });

        DayTextField.setForeground(java.awt.Color.lightGray);
        DayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayTextFieldActionPerformed(evt);
            }
        });
        DayTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DayTextFieldKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel6.setText("End Time");

        HourTextField.setForeground(java.awt.Color.lightGray);
        HourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HourTextFieldActionPerformed(evt);
            }
        });

        MinutesTextField.setForeground(java.awt.Color.lightGray);
        MinutesTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MinutesTextFieldKeyPressed(evt);
            }
        });

        jLabel8.setText("/");

        jLabel9.setText("/");

        jLabel10.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(410, 410, 410))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titleTextField)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(YesRadioButton)
                                .addGap(50, 50, 50)
                                .addComponent(NoRadioButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(HourTextField)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(YearTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MonthTextField)
                                    .addComponent(MinutesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(QuestionNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(QuestionNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinutesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesRadioButton)
                    .addComponent(NoRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String title = titleTextField.getText();
        
        String QN = QuestionNumberTextField.getText();
        QuesNo = Integer.parseInt(QN);
        
        String y = YearTextField.getText();
        String m = MonthTextField.getText();
        String d = DayTextField.getText();
        
        String h = HourTextField.getText();
        String min = MinutesTextField.getText();
        
        String disGrade = YesRadioButton.isSelected()?"TRUE":"FALSE";
        
        String quizID = getID();
        qid = quizID;
        
        if(isDateValid(y, m, d) && isTimeValid(h, min) && isQestionNumberValid(QN)){
            System.out.println(getFormattedDate(y, m, d, h, min));
            System.out.println(quizID);
            try{
                st = c.prepareStatement("INSERT INTO QUIZ (qid, rid, title, QN, endDate, displayGrade) VALUES (?,?,?,CAST(? AS INT),CAST(? AS TIMESTAMP),CAST(? AS BOOLEAN))");
                st.setString(1, quizID);
                st.setString(2, Dbms.currentRoom.getRoom());// Want to change.
                st.setString(3, title);
                st.setString(4,QN);
                st.setString(5, getFormattedDate(y, m, d, h, min));
                st.setString(6, disGrade);
                st.executeUpdate();
            }catch(SQLException ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(this, "Error");
            }
        }
        SQU.setVisible(true);
        setQuestions.counter = 0;
    }//GEN-LAST:event_jButton1ActionPerformed
    private String getFormattedDate(String y, String m, String d, String h, String min){
        String formattedDate = "";
        
        formattedDate += y;
        formattedDate += "-";
        
        if(m.length() == 1)
            m = "0" + m;
        formattedDate += m;
        formattedDate += "-";
        
        if(d.length() == 1)
            d = "0" + d;
        formattedDate += d;
        formattedDate += " ";
        
        if(h.length() == 1)
            h = "0" + h;
        formattedDate += h;
        formattedDate += ":";
        
        if(min.length() == 1)
            min = "0" + min;
        formattedDate += min;
        formattedDate += ":";
        
        formattedDate += "00.000000";
        
        return formattedDate;
    } 
    private String getID(){
         String alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
         String id = "";
         Random random = new Random();
         for(int i = 0;i < 10; i++){
             int idx = random.nextInt(alphabet.length());
             id += alphabet.charAt(idx);
         }
         return id;
    }
    private boolean isQestionNumberValid(String QN){
        String n = QuestionNumberTextField.getText();
        try{
            Integer.parseInt(n);
        }catch(Exception ex){
            return false;
        }
        if(Integer.parseInt(n) < 1){
            return false;
        }
        else 
            return true;
    }
    private boolean isDateValid(String y, String m, String d){
        try{
            Integer.parseInt(y);
            Integer.parseInt(m);
            Integer.parseInt(d);
        }catch(Exception ex){
            return false;
        }
        if(Integer.parseInt(y) < 2023){
            return false;
        }
        else if(Integer.parseInt(m) > 12 || Integer.parseInt(m) < 1){
            return false;
        }
        else if(Integer.parseInt(d) > 31 || Integer.parseInt(d) < 0){
            return false;
        }
        else
            return true;
    }
    private boolean isTimeValid(String h, String min){ 
        try{
            Integer.parseInt(h);
            Integer.parseInt(min);
        }catch(Exception ex){
            return false;
        }
        if(Integer.parseInt(h) > 24 || Integer.parseInt(h) < 0){
            return false;
        }
        else if(Integer.parseInt(min) > 59 || Integer.parseInt(min) < 0){
            return false;
        }
        else 
            return true;
    }
    private void titleTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleTextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            QuestionNumberTextField.requestFocus();
        }
    }//GEN-LAST:event_titleTextFieldKeyPressed
        
    private void QuestionNumberTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuestionNumberTextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            YearTextField.requestFocus();
        }
    }//GEN-LAST:event_QuestionNumberTextFieldKeyPressed

    private void MonthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthTextFieldActionPerformed

    private void DayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayTextFieldActionPerformed

    private void YearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearTextFieldActionPerformed

    private void YearTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YearTextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            MonthTextField.requestFocus();
        }
    }//GEN-LAST:event_YearTextFieldKeyPressed

    private void MonthTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonthTextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            DayTextField.requestFocus();
        }
    }//GEN-LAST:event_MonthTextFieldKeyPressed

    private void DayTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DayTextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            HourTextField.requestFocus();
        }
    }//GEN-LAST:event_DayTextFieldKeyPressed

    private void MinutesTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MinutesTextFieldKeyPressed

    }//GEN-LAST:event_MinutesTextFieldKeyPressed

    private void HourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HourTextFieldActionPerformed

    private void YearTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_YearTextFieldFocusGained
        if(YearTextField.getText().equals("Year")){
            
        }
    }//GEN-LAST:event_YearTextFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makeQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DayTextField;
    private javax.swing.JTextField HourTextField;
    private javax.swing.JTextField MinutesTextField;
    private javax.swing.JTextField MonthTextField;
    private javax.swing.JRadioButton NoRadioButton;
    private javax.swing.JTextField QuestionNumberTextField;
    private javax.swing.JTextField YearTextField;
    private javax.swing.JRadioButton YesRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
