/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Yaseen
 */
public class takeQuiz extends javax.swing.JFrame {

    /**
     * Creates new form takeQuiz
     */
    
    Connection c = dbms.Dbms.DBcon();
    PreparedStatement st = null;
    ResultSet rs;
    
    
    public static String qid = null;
    public static int noq = 0;
    public ArrayList<String> statments = new ArrayList();
    public ArrayList<String> opt1 = new ArrayList();
    public ArrayList<String> opt2 = new ArrayList();
    public ArrayList<String> opt3 = new ArrayList();
    public ArrayList<String> opt4 = new ArrayList();
    public ArrayList<Integer> coi = new ArrayList();
    public int ind = 0;
    boolean[] wist = null;
    int grade = 0;
    public takeQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        qn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        qnum = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        qst = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 17, 17));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/output-onlinepngtools.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(857, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        qn.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        qn.setText("Quiz Name");

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setText("Question : ");

        qnum.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        qnum.setText("number");

        qst.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        qst.setText("Question Statment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qst)
                .addContainerGap(380, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qst)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        buttonGroup1.add(op1);
        op1.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        op1.setText("Option1");

        buttonGroup1.add(op2);
        op2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        op2.setText("Option2");

        buttonGroup1.add(op3);
        op3.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        op3.setText("Option3");

        buttonGroup1.add(op4);
        op4.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        op4.setText("Option4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(op1)
                    .addComponent(op2)
                    .addComponent(op3)
                    .addComponent(op4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(op1)
                .addGap(18, 18, 18)
                .addComponent(op2)
                .addGap(18, 18, 18)
                .addComponent(op3)
                .addGap(18, 18, 18)
                .addComponent(op4)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        next.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(qn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qnum))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(next)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qn)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(qnum))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(next)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        mark();
        if(ind < noq - 1){
            ind++;
            buttonGroup1.clearSelection();
            qnum.setText(ind+1+"");
            qst.setText(statments.get(ind));
            op1.setText(opt1.get(ind));
            op2.setText(opt2.get(ind));
            op3.setText(opt3.get(ind));
            op4.setText(opt4.get(ind));
        }else{
            JOptionPane.showMessageDialog(this, "Quiz Ended");
            calcGrade();
            System.out.println(Arrays.toString(wist));
            JOptionPane.showMessageDialog(this, "You Got "+grade+"%");
            insertGrade();
        }
    }//GEN-LAST:event_nextActionPerformed
    
    public void insertGrade(){
        try{
            st = c.prepareStatement("INSERT INTO GRADE (value, assignedTo, rid, qid) VALUES (?,?,?,?)");
            st.setInt(1, (int)Math.ceil(grade));
            st.setString(2, Dbms.userData.getUser());
            st.setString(3, Dbms.currentRoom.getRoom());
            st.setString(4, qid);
            st.executeUpdate();
        }catch(SQLException exc){
            System.out.println(exc);
        }
    }
    public void calcGrade(){
        int count = 0;
        for (int i = 0; i < noq; i++) {
            if(wist[i] == true){
                count++;
            }
        }
        grade = (int)Math.ceil((count*1.0/noq*1.0)*100);
    }
    public void mark(){
        if(op1.isSelected()){
            wist[ind] = coi.get(ind) == 1;
        }else if(op2.isSelected()){
            wist[ind] = coi.get(ind) == 2;
        }else if(op3.isSelected()){
            wist[ind] = coi.get(ind) == 3;
        }else if(op4.isSelected()){
            wist[ind] = coi.get(ind) == 4;
        }
    }
    public void init(){
        ind = 0;
        statments.clear();
        opt1.clear();
        opt2.clear();
        opt3.clear();
        opt4.clear();
        try{
            st = c.prepareStatement("SELECT COUNT(*) AS num_questions FROM QUESTIONS WHERE qid = ?");
            st.setString(1, qid);
            rs = st.executeQuery();        
            if(rs.next()){
                noq = rs.getInt("num_questions");
                System.out.println(noq);
                wist = new boolean[noq];
            }
        }catch(SQLException exc){
            System.out.println(exc);
        }
        try{
            st = c.prepareStatement("SELECT * FROM QUESTIONS WHERE qid = ?");
            st.setString(1, qid);
            rs = st.executeQuery();        
            while(rs.next()){
                statments.add(rs.getString("statement"));
                opt1.add(rs.getString("option1"));
                opt2.add(rs.getString("option2"));
                opt3.add(rs.getString("option3"));
                opt4.add(rs.getString("option4"));
                coi.add(rs.getInt("coi"));
            }
        }catch(SQLException exc){
            System.out.println(exc);
        }
        qnum.setText(ind+1+"");
        qst.setText(statments.get(ind));
        op1.setText(opt1.get(ind));
        op2.setText(opt2.get(ind));
        op3.setText(opt3.get(ind));
        op4.setText(opt4.get(ind));
        System.out.println(statments.toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(takeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(takeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(takeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(takeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new takeQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton next;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    public static javax.swing.JLabel qn;
    private javax.swing.JLabel qnum;
    private javax.swing.JLabel qst;
    // End of variables declaration//GEN-END:variables
}
